soft_hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # hand_soft_hand_synergy_joint_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: soft_hand_synergy_joint
  #   pid: {p: 1.0, i: 0.1, d: 0.5}
    
  # Position Controllers ---------------------------------------
  hand_thumb_abd_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_thumb_abd_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_thumb_inner_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_thumb_inner_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_thumb_outer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_thumb_outer_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_abd_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_abd_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_inner_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_inner_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_middle_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_middle_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_outer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_outer_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_abd_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_abd_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_inner_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_inner_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_middle_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_middle_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_outer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_outer_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_abd_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_abd_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_inner_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_inner_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_middle_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_middle_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_outer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_outer_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_abd_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_abd_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_inner_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_inner_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_middle_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_middle_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_outer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_outer_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

  # mimic joints
  hand_thumb_inner_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_thumb_inner_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_thumb_outer_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_thumb_outer_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_inner_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_inner_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_middle_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_middle_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_index_outer_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_index_outer_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_inner_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_inner_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_middle_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_middle_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_middle_outer_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_middle_outer_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_inner_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_inner_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_middle_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_middle_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_ring_outer_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_ring_outer_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_inner_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_inner_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_middle_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_middle_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  hand_little_outer_joint_mimic_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_little_outer_joint_mimic
    pid: {p: 1.0, i: 0.1, d: 0.5}

  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:  
      - soft_hand_thumb_abd_joint
      - soft_hand_thumb_inner_joint
      - soft_hand_thumb_outer_joint
      - soft_hand_index_abd_joint
      - soft_hand_index_inner_joint
      - soft_hand_index_middle_joint
      - soft_hand_index_outer_joint
      - soft_hand_middle_abd_joint
      - soft_hand_middle_inner_joint
      - soft_hand_middle_middle_joint
      - soft_hand_middle_outer_joint
      - soft_hand_ring_abd_joint
      - soft_hand_ring_inner_joint
      - soft_hand_ring_middle_joint
      - soft_hand_ring_outer_joint
      - soft_hand_little_abd_joint
      - soft_hand_little_inner_joint
      - soft_hand_little_middle_joint
      - soft_hand_little_outer_joint
      - soft_hand_thumb_inner_joint_mimic
      - soft_hand_thumb_outer_joint_mimic
      - soft_hand_index_inner_joint_mimic
      - soft_hand_index_middle_joint_mimic
      - soft_hand_index_outer_joint_mimic
      - soft_hand_middle_inner_joint_mimic
      - soft_hand_middle_middle_joint_mimic
      - soft_hand_middle_outer_joint_mimic
      - soft_hand_ring_middle_joint_mimic
      - soft_hand_ring_inner_joint_mimic
      - soft_hand_ring_outer_joint_mimic
      - soft_hand_little_inner_joint_mimic
      - soft_hand_little_middle_joint_mimic
      - soft_hand_little_outer_joint_mimic
      
      
      
      
      
      
      
     